<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'flux\\cli\\app' => '/cli/App.php',
                'flux\\cli\\command' => '/cli/Commands.php',
                'flux\\cli\\commandcontext' => '/cli/CommandContext.php',
                'flux\\cli\\configuration' => '/cli/Configuration.php',
                'flux\\cli\\driver' => '/cli/Drivers.php',
                'flux\\cli\\flags' => '/cli/Flags.php',
                'flux\\cmd\\command' => '/cmd/Command.php',
                'flux\\cmd\\execscript' => '/cmd/ExecScript.php',
                'flux\\cmd\\help' => '/cmd/Help.php',
                'flux\\lib\\data' => '/lib/Data.php',
                'flux\\lib\\datacollection' => '/lib/DataCollection.php',
                'flux\\lib\\datafield' => '/lib/DataField.php',
                'flux\\lib\\datavalidator' => '/lib/DataValidator.php',
                'flux\\lib\\executor' => '/lib/Executor.php',
                'flux\\lib\\query' => '/lib/Query.php',
                'flux\\sqliteexecutor' => '/SQLiteExecutor.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
