<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'flux\\lib\\data' => '/lib/Data.php',
                'flux\\lib\\datacollection' => '/lib/DataCollection.php',
                'flux\\lib\\datavalidator' => '/lib/DataValidator.php',
                'flux\\lib\\executor' => '/lib/Executor.php',
                'flux\\sqliteexecutor' => '/SQLiteExecutor.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
